services:
  - type: web
    name: studyswap
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATA_DIR
        value: /tmp/studyswap
      - key: SECRET_KEY
        generateValue: true
